### ISSUE TITLE
StakingValidator Script Role

### ISSUE THREAD

**Issue by SeungheonOh** [mlabs-haskell/ply#37]
We only have validators and minting policy, but no staking. I would be nice to have that as well

**Comment by TotallyNotChase** [comment]
How would one distinguish it from a minting policy though? e.g in `RoleOf`

**Comment by SeungheonOh** [comment]
User need to specify the type

**Comment by TotallyNotChase** [comment]
I don't like making users specify the type. The practical benefit provided by having a purely cosmetic `StakingValidator` script role (one can just use a `TypedScript MintingPolicyRole` as a stake validator) is too small to take away the ability to infer script roles. It'd be nice if there was some middle ground, e.g users only having to _override_ an inferred `MintingPolicyRole` with a `StakingValidatorRole`. But I don't know how this could be made explicit.

`MintingPolicyRole` could be renamed to `PolicyRole`, but I don't really see what that'd achieve (is it just a cosmetic benefit, simply indicating that it may be a stake validator or a minting policy?)

**Comment by SeungheonOh** [comment]
yeah, I don't think we should really break API at this point. I don't think there's any other good solution for this. I'll reopen if I fount one, Thanks!
