### ISSUE TITLE
ADT discards information about its type variable

### ISSUE THREAD

**Issue by SeungheonOh** [mlabs-haskell/ply#42]
```hs
$> typeName @(Int, Int)
GHC.Tuple:(,)
```

It's best to deprecate them IMO

**Comment by SeungheonOh** [comment]
Or else, also possible to deprecate current `Ply.Core.Typename` and use type families

**Comment by TotallyNotChase** [comment]
I suppose type families really are starting to look like the only option

**Comment by SeungheonOh** [comment]
fixed by agda2

**Comment by SeungheonOh** [comment]
fixed by c01fbb227cb9cd5f8c42335214bef79b92dc3166
