### ISSUE TITLE
Why no "type" field in envelope?

### ISSUE THREAD

**Issue by zmrocze** [mlabs-haskell/ply#46]
Script `.plutus` files are expected to have this structure:
```
{  "type": "PlutusScriptV1",
    "description": "password_validator",
    "cborHex": "5843584101000022223232323"
}
```
and ply yields:
```
{
    "cborHex": "5901a",
    "description": "nft_hash_applied",
    "params": [
        "PlutusLedgerApi.V1.Tx:TxOutRef",
        "PlutusLedgerApi.V1.Value:TokenName"
    ],
    "rawHex": "5901a501000032323232323",
    "role": "MintingPolicyRole",
    "version": "ScriptV1"
}
```
so ply expands on this providing more type information with additional fields. But the field "type" is missing, in the end making the envelope incompatible with `.plutus` still. Wouldn't it be good for the ply format to be a clean extension of `.plutus` format, integrating with `ctl`/`cardano-api` etc?

**Comment by SeungheonOh** [comment]
I don't think there's a formally declared definition of `.plutus` file that being said, type field can easily added if needed

**Comment by SeungheonOh** [comment]
IMO, I need to add function that writes `.plutus` while ensuring there's no more parameters left to apply. I'm mainly concerned about people mistakenly use scripts that needs to be applied with parameters as regular policy or validator. 

ply export, in a sense, is not really meant to be `.plutus`, and they weren't meant to be used as `ScriptEnevelope` directly. 

the function I mentioned on top would look like:
```hs
writePlutusEnvelope :: FilePath -> TypedScript _ '[] -> IO ()
```
It makes explicit that only ready-to-go policies and validators can be exported to `.plutus`

**Comment by SeungheonOh** [comment]
I'll update the example export's filename as it can be misleading a bit

**Comment by zmrocze** [comment]
But what is the problem with saving partially-applied scripts?

**Comment by zmrocze** [comment]
For me - this compatibility with cardano-api and the rest would make things much easier. I can also imagine that working out of the box with plenty of other tools is an advantage. Many like 

The counter argument is that the "type" field is redundant as it follows from the "version" field. 

If you guys agree to implement it, we could on scaffold budget (I can implement or you guys can).

**Comment by SeungheonOh** [comment]
https://github.com/mlabs-haskell/ply/pull/47
