### ISSUE TITLE
Encoding issue while applying arguments to TypedScript

### ISSUE THREAD

**Issue by Swordlash** [mlabs-haskell/ply#53]
# Scenario
Consider the following validator that passes if the parameter is an ada currency symbol:
```
validator :: ClosedTerm (PCurrencySymbol :--> PData :--> PData :--> PScriptContext :--> POpaque)
validator = plam $ \cs _ _ _ ->
  pif (pdata cs #== padaSymbolData) (popaque $ pcon PUnit) perror
```

now, let's create a `TypedScript` and apply the `adaSymbol` to it, then evaluate it with dummy arguments (passing `()` as script context as it doesn't matter here)
```
script :: TypedScript 'ThreeArgumentScript '[CurrencySymbol]
Right script = toTypedScript NoTracing validator 

TypedScript _ prog = script Ply.# adaSymbol
result = applyArguments (Script prog) [toData (), toData (), toData ()]

case evalScript result of
          (Left err, _, _) -> assertFailure $ show err
          (Right{}, _, _) -> pure ()
```

## Expectation
Validator passes, with `evalScript` returning `Right` in first element of tuple.

## Reality
CEK machine throws
```
An error has occurred:
Could not unlift a value:
Type mismatch: expected: data; actual: bytestring
Caused by: (equalsData # (B #))
```

There seems to be a mismatch in what Plutarch expects (data-wrapped bytestring) and what Ply provides (bare bytestring).

**Comment by Swordlash** [comment]
FYI we're using `staging` branch of Plutarch.

**Comment by TotallyNotChase** [comment]
Does the same thing happen when using `#!`?

**Comment by TotallyNotChase** [comment]
Seems to work just fine on the `master` branch of Ply. Whichever issue you're facing must be a newly introduced bug on the branch you're using. Judging by the `ThreeArgumentScript` moniker - it's not a branch I'm aware of or have worked on.
