### ISSUE TITLE
Possibly incorrect substitution definition inside `applyConstant`

### ISSUE THREAD

**Issue by sourabhxyz** [mlabs-haskell/ply#54]
https://github.com/mlabs-haskell/ply/blob/efeb0baddffccdbbf38d1e7e02cd1778422eeb78/ply-core/src/Ply/Core/UPLC.hs#L35

reads `subst 1 (const body) f` which appears weird as there is no use of `c` being made here, shouldn't it instead be something along the lines `subst 1 (const arg) body`?

**Comment by TotallyNotChase** [comment]
I think you're right. This seems like a nasty bug that probably only got unchecked because real scripts usually don't apply small constants.
